### ISSUE TITLE
Use inrupt/solid-style-guide instead of main.css

### ISSUE THREAD

**Issue by tcyrus** [inrupt/solid-idp#29]
It makes more sense to copy `main.css` from [solid-style-guide](https://github.com/inrupt/solid-style-guide/blob/master/css/main.css) than to keep a [copy](https://github.com/inrupt/solid-idp/blob/master/src/defaultConfiguration/views/main.css) in the `src` of this repo.

**Comment by jaxoncreed** [comment]
I believe it is bad practice to host stylesheets on github. If the stylesheet is changed with breaking changes it will cause style problems on the site.
